language: cpp
sudo: false
dist: jammy

compiler:
  - gcc
os:
  - linux

# ruby: 2.2.0

before_install:
  - echo $LANG
  - echo $LC_ALL

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then ./build.sh; fi

env:
  - HK_EXT=https://raw.githubusercontent.com/DiscordHooks/

after_success:
  - wget $HK_EXT/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget $HK_EXT/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

branches:
  only:
    - master
